from typing import Final

POSITION_KEYWORDS: Final = (
    "박사후연구원",
    "박사후 연구원",
    "postdoctoral researcher",
    "post-doctoral researcher",
    "post-doc",
    "postdoc",
    "연구교수",
    "research professor",
    "assistant professor",
    "tenure track",
    "tenure-track",
    "faculty position",
    "research faculty",
    "contract professor",
    "조교수",
    "전임교원",
    "계약교수",
    "연구과제전담교수",
    "프로젝트교수",
    "project professor",
    "faculty track",
    "책임연구원",
    "principal researcher",
    "선임연구원",
    "senior researcher",
    "전임연구원",
    "정규직 연구",
    "연구직",
    "위촉연구원",
    "석사후연구원",
    "research scientist",
    "scientist",
    "researcher",
    "연구원",
)
