from __future__ import annotations

from typing import Final

from .rule_models import WeightedKeywordRule
from .taxonomy import GENERAL_CHEMISTRY_MATERIALS

POSITIVE_RULES: Final = (
    WeightedKeywordRule(
        "Organic semiconductor / organic electronics",
        15,
        (
            "organic semiconductor",
            "organic electronics",
            "organic optoelectronics",
            "organic photovoltaic",
            "organic photonics",
            "conjugated polymer",
            "polymer semiconductor",
            "semiconducting polymer",
            "molecular semiconductor",
            "electronic materials",
            "functional organic materials",
            "유기반도체",
            "유기전자",
            "유기광전자",
            "공액고분자",
            "고분자 반도체",
        ),
    ),
    WeightedKeywordRule(
        "Polymer synthesis / polymer chemistry",
        12,
        (
            "polymer synthesis",
            "polymer chemistry",
            "polymer semiconductor",
            "functional polymer",
            "macromolecular chemistry",
            "monomer synthesis",
            "고분자 합성",
            "고분자 화학",
            "고분자 반도체",
            "기능성 고분자",
            "단량체 합성",
        ),
    ),
    WeightedKeywordRule(
        "Organic synthesis / functional molecules",
        10,
        (
            "organic synthesis",
            "molecular design",
            "functional molecules",
            "organic materials",
            "유기합성",
            "분자설계",
            "기능성 분자",
            "유기소재",
        ),
    ),
    WeightedKeywordRule(
        "Functional materials",
        10,
        (
            "functional material",
            "functional polymer",
            "smart material",
            "기능성 소재",
            "기능성 고분자",
            "기능성 유기소재",
        ),
    ),
    WeightedKeywordRule(
        "Advanced materials chemistry",
        10,
        (
            "advanced materials",
            "nanomaterials",
            "materials chemistry",
            "materials science",
            "첨단소재",
            "나노소재",
            "소재화학",
            "재료화학",
            "신소재",
        ),
    ),
    WeightedKeywordRule(
        "Energy materials",
        8,
        (
            "energy materials",
            "energy conversion",
            "energy storage",
            "battery materials",
            "fuel cell",
            "electrode materials",
            "에너지 소재",
            "에너지 변환",
            "에너지 저장",
            "배터리 소재",
            "연료전지",
            "전극 소재",
        ),
    ),
    WeightedKeywordRule(
        "Electrochemistry",
        8,
        (
            "electrochemistry",
            "electrochemical materials",
            "electrochemical device",
            "electrocatalysis",
            "전기화학",
            "전기화학 소재",
            "전기촉매",
        ),
    ),
    WeightedKeywordRule(
        "Photocatalysis",
        10,
        ("photocatalysis", "photocatalytic", "광촉매"),
    ),
    WeightedKeywordRule(
        "Hydrogen energy",
        8,
        (
            "hydrogen energy",
            "hydrogen production",
            "hydrogen evolution",
            "water splitting",
            "hydrogen sensor",
            "수소 생산",
            "수소생산",
            "수소 센서",
            "수전해",
        ),
    ),
    WeightedKeywordRule(
        "Photoelectrochemistry",
        10,
        ("photoelectrochemistry", "photoelectrochemical", "광전기화학"),
    ),
    WeightedKeywordRule(
        "Semiconductor materials",
        8,
        (
            "semiconductor materials",
            "polymer semiconductor",
            "molecular semiconductor",
            "반도체 소재",
            "고분자 반도체",
        ),
    ),
    WeightedKeywordRule(
        "Device physics / thin-film devices",
        8,
        (
            "device physics",
            "thin film device",
            "thin-film device",
            "thin film transistor",
            "device fabrication",
            "optoelectronic device",
            "소자물리",
            "박막트랜지스터",
            "소자 제작",
            "광전자 소자",
            "광전소자",
        ),
    ),
    WeightedKeywordRule(
        "Interface engineering / charge transport",
        8,
        (
            "interface engineering",
            "interface physics",
            "charge transfer",
            "charge transport",
            "carrier mobility",
            "n-type sam",
            "계면제어",
            "계면 물리",
            "계면 전하이동",
            "계면 전하 이동",
            "전하 이동",
        ),
    ),
    WeightedKeywordRule(
        "Sensor materials",
        6,
        (
            "sensor materials",
            "chemical sensor",
            "gas sensor",
            "hydrogen sensor",
            "센서 소재",
            "가스센서",
            "수소 센서",
        ),
    ),
    WeightedKeywordRule(
        "General chemistry / materials",
        5,
        GENERAL_CHEMISTRY_MATERIALS.keywords,
    ),
)
