"""National seed registry, expanded through KCUE; seeds are not verified boards.

A discovery seed is counted as covered only after actual notices are read.
Faculty recruitment links are followed from the institution's own homepage.
"""
UNIVERSITIES = (
    ("SOGANG", "서강대학교", "https://www.sogang.ac.kr/"),
    ("CAU", "중앙대학교", "https://www.cau.ac.kr/cms/FR_CON/index.do?MENU_ID=1670"),
    ("KHU", "경희대학교", "https://www.khu.ac.kr/"),
    ("KONKUK", "건국대학교", "https://www.konkuk.ac.kr/"),
    ("DONGGUK", "동국대학교", "https://www.dongguk.edu/"),
    ("EWHA", "이화여자대학교", "https://www.ewha.ac.kr/"),
    ("SOOKMYUNG", "숙명여자대학교", "https://www.sookmyung.ac.kr/"),
    ("SSU", "숭실대학교", "https://www.ssu.ac.kr/"),
    ("SEJONG", "세종대학교", "https://www.sejong.ac.kr/"),
    ("AJOU", "아주대학교", "https://www.ajou.ac.kr/"),
    ("INHA", "인하대학교", "https://www.inha.ac.kr/"),
    ("INU", "인천대학교", "https://www.inu.ac.kr/"),
    ("SEOULTECH", "서울과학기술대학교", "https://www.seoultech.ac.kr/"),
    ("KOOKMIN", "국민대학교", "https://www.kookmin.ac.kr/"),
    ("DANKOOK", "단국대학교", "https://www.dankook.ac.kr/"),
    ("GACHON", "가천대학교", "https://www.gachon.ac.kr/"),
    ("TUKOREA", "한국공학대학교", "https://www.tukorea.ac.kr/"),
    ("UOS", "서울시립대학교", "https://www.uos.ac.kr/"),
    ("HONGIK", "홍익대학교", "https://www.hongik.ac.kr/"),
    ("MYONGJI", "명지대학교", "https://www.mju.ac.kr/"),
    ("KWANGWOON", "광운대학교", "https://www.kw.ac.kr/"),
    ("CATHOLIC", "가톨릭대학교", "https://www.catholic.ac.kr/"),
    ("CNU", "충남대학교", "https://plus.cnu.ac.kr/_prog/_board/?code=sub07_0705&menu_dvs_cd=0705&site_dvs_cd=kr"),
    ("CBNU", "충북대학교", "https://www.chungbuk.ac.kr/"),
    ("KONGJU", "국립공주대학교", "https://www.kongju.ac.kr/"),
    ("UT", "국립한국교통대학교", "https://www.ut.ac.kr/"),
    ("KOREATECH", "한국기술교육대학교", "https://www.koreatech.ac.kr/"),
    ("HANBAT", "국립한밭대학교", "https://www.hanbat.ac.kr/"),
    ("SCH", "순천향대학교", "https://www.sch.ac.kr/"),
    ("SUNMOON", "선문대학교", "https://www.sunmoon.ac.kr/"),
    ("HOSEO", "호서대학교", "https://www.hoseo.ac.kr/"),
    ("KANGWON", "강원대학교", "https://www.kangwon.ac.kr/"),
    ("HALLYM", "한림대학교", "https://www.hallym.ac.kr/"),
    ("GNU", "경상국립대학교", "https://www.gnu.ac.kr/"),
    ("ULSAN", "울산대학교", "https://www.ulsan.ac.kr/"),
    ("YU", "영남대학교", "https://www.yu.ac.kr/"),
    ("KMU", "계명대학교", "https://www.kmu.ac.kr/"),
    ("DONGA", "동아대학교", "https://www.donga.ac.kr/"),
    ("DEU", "동의대학교", "https://www.deu.ac.kr/"),
    ("CHANGWON", "국립창원대학교", "https://www.changwon.ac.kr/"),
    ("KUMOH", "국립금오공과대학교", "https://www.kumoh.ac.kr/"),
    ("KS", "경성대학교", "https://www.ks.ac.kr/"),
    ("JNU", "전남대학교", "https://hangj.jnu.ac.kr/"),
    ("JBNU", "전북대학교", "https://www.jbnu.ac.kr/"),
    ("CHOSUN", "조선대학교", "https://www.chosun.ac.kr/"),
    ("WKU", "원광대학교", "https://www.wku.ac.kr/"),
    ("KUNSAN", "국립군산대학교", "https://www.kunsan.ac.kr/"),
    ("SCNU", "국립순천대학교", "https://www.scnu.ac.kr/"),
    ("MOKPO", "국립목포대학교", "https://www.mokpo.ac.kr/"),
    ("JEJU", "제주대학교", "https://www.jejunu.ac.kr/"),
    ("JJ", "전주대학교", "https://www.jj.ac.kr/"),
    ("KENTECH", "한국에너지공과대학교", "https://www.kentech.ac.kr/"),
)
ADDITIONAL_INSTITUTES = (
    ("KICET", "한국세라믹기술원", "https://www.kicet.re.kr/"),
    ("KETI", "한국전자기술연구원", "https://www.keti.re.kr/"),
    ("NNFC", "나노종합기술원", "https://www.nnfc.re.kr/"),
    ("KANC", "한국나노기술원", "https://www.kanc.re.kr/"),
)
